version: "3"

services:
  server-eleccion:
    container_name: server-eleccion
    build:
      context: C:\\Users\\Moino\\Documents\\1er2021\\sa\\lab\\practica8
    restart: always
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: C:\\Users\\Moino\\Documents\\1er2021\\sa\\lab\\practica8server
        target: /usr/src/app/server
    command: bash -c "npm run start"

  db-mysql:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      - MYSQL_DATABASE=practica8
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    volumes:
      - type: volume
        source: db_persistent_data
        target: /var/lib/mysql
        volume:
         nocopy: true

  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
networks:
  sonarnet:

volumes:
    db_persistent_data:
      driver: local
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    sonarqube_temp:
    postgresql:
    postgresql_data:
    sonarqube_conf:
    sonarqube_bundled-plugins: